### PR TITLE
Implement liquidator

### PR DESCRIPTION
**Pull request by takami-ml**
## Changes
Implemented liquidator
* List of all pairs of trader and baseToken is implemented by monitoring the event logs.
* The events monitored are `LiquidityChanged` and `PositionChanged.`

## To-dos before merge
- [x] add event_indexer test
- [x] add liquidator test
- [x] add CI script
- [ ] Confirmation in testnet

### CODE REVIEW

**Comment by richmanbtc** [comment]
I am wondering if the gas bill will be consumed if liquidation is not possible.

**Comment by takami-ml** [comment]
> I am wondering if the gas bill will be consumed if liquidation is not possible.

Add changes. Now liquidator
1. checks the trader's margin is enough or not. if yes, then liquidation will be skipped
2. checks the order has order or not. if no, then cancelOrder will be skipped

**Comment by richmanbtc** [comment]
>checks the order has order or not. if no, then cancelOrder will be skipped

It looks like this condition is not implemented.

https://github.com/perpdex/perpdex-contract/blob/develop/contracts/ClearingHousePerpdex.sol#L559

If you use the method of simulating execution and skipping when it is reverted, I feel that it will be less affected by the specification change on the contract.

**Comment by takami-ml** [comment]
> It looks like this condition is not implemented.

Thank you for the review.
I will add this condition too.

> If you use the method of simulating execution and skipping when it is reverted, I feel that it will be less affected by the specification change on the contract.

Please let me ask for details so that I will get your suggestion correctly :pray:

* Is there any way to simulate liquidation without transaction call?
* Or, do you suggest it's better to call liquidate method without checking conditions?
  * I think I have to pay gas fees even for the reverted transactions. It would be better to avoid as much as possible.

**Comment by richmanbtc** [comment]
>Is there any way to simulate liquidation without transaction call?

I think that it can be judged by the success or failure of estimateGas.

**Comment by takami-ml** [comment]
Thank you. I didn't know that method. It seems very convenient and fits my case.

* https://ethereum.stackexchange.com/questions/121577/how-does-web3-js-estimate-gas-required-for-a-tx-using-the-estimategas-method/121580#121580

In summary, I will do the followings.
* remove `_is_margin_enough_for_maintenance`
* remove `_has_order`
* Instead, implement checking method with using estimateGas respectively

**Comment by takami-ml** [comment]
Changed added.

If it seems ok, I would like to merge this PR.
I will confirm on testnet after perp-ui bug fix gets done.

**Pull request merged**
